# dev-workflow.yml
name: CI Dev Workflow

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: lts/*

      - name: Install deps
        run: npm ci

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: lts/*

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test

  pull-request:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
